name: log data on comment

on:
    pull_request_review:
      types: [submitted]
  
jobs:
    logger:
      runs-on: ubuntu-latest
      steps:
        - run: echo "This PR was approved"
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log pull request number and JSON info
          run: |
               echo "Pull Request Number: ${{ github.event.review.state}}"
               echo "Reviewers: ${{ toJson(github.event.pull_request.requested_reviewers) }}"
               echo "Mergeable: ${{ toJson(github.event.pull_request) }}"