name: log data on comment

on:
    pull_request_review_comment:
      types: [created, deleted, edited]
  
jobs:
    logger:
      runs-on: ubuntu-latest
      steps:
        - run: echo "This PR was approved"
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log pull request number and JSON info
          run: |
               echo "Reviewers: ${{ toJson(github.event.pull_request.requested_reviewers) }}"
               echo "review: ${{ toJson(github.event.review) }}"
               echo "Mergeable: ${{ toJson(github.event.pull_request.review) }}"