name: Add `preview` tag

on:
    pull_request_review:
      types: [submitted]
  
jobs:
    approved:
      if: github.event.review.state == 'approved' 
      runs-on: ubuntu-latest
      steps:
        - run: echo "This PR was approved"
        - name: Checkout code
          uses: actions/checkout@v2
             
        - name: Add 'preview' tag to pull request
          if: ${{ github.event.pull_request.requested_reviewers == null || github.event.pull_request.requested_reviewers.length == 0 }}
          run: gh pr edit ${{ github.event.pull_request.number }} --add-label 'preview'
          env:
            GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}