name: Add `preview` tag

on:
    pull_request_review:
      types: [submitted]
  
jobs:
    approved:
      if: github.event.review.state == 'approved'
      runs-on: ubuntu-latest
      steps:
        - run: echo "This PR was approved"
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log pull request number and JSON info
          run: |
            echo "Pull Request Number: ${{ github.event.review.state}}"